export default {
 GET_PRODUCTS: 'GET_PRODUCTS',
 GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
 GET_PRODUCTS_ERROR: 'GET_PRODUCTS_ERROR',
 ADD_PRODUCT: 'ADD_PRODUCT',
 ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
 ADD_PRODUCT_ERROR: 'ADD_PRODUCT_ERROR',
 GET_CART: 'GET_CART',
 GET_CART_SUCCESS: 'GET_CART_SUCCESS',
 GET_CART_FAILED: 'GET_CART_FAILED',
 ADD_TO_CART: 'ADD_TO_CART',
 ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
 ADD_TO_CART_FAILED: 'ADD_TO_CART_FAILED',
 GET_PRODUCT: 'GET_PRODUCT',
 GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
 GET_PRODUCT_FAILED: 'GET_PRODUCT_FAILED'
}